import numpy as np
from abc import ABC, abstractmethod
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel

from ..unit_level_models.base_class import BaseTDDBModel

# ==============================================================================
# 2. Wafer-Level Engine Base Class / Wafer 级别晶圆流水线基类
# ==============================================================================
class BaseWaferEngine(ABC):
    """
    Abstract Base Class for Wafer-Level reliability aggregation.
    Provides generic spatial interpolation and vectorized weakest-link solvers.
    
    晶圆级可靠性汇总模型的抽象基类。
    提供通用的空间插值方法与向量化最薄弱环节求解器。
    """
    def __init__(self, M_structures: float = 1e6, F_target: float = 1e-4):
        """
        Initialize the wafer-level engine. / 初始化晶圆级流水线。
        
        Args:
            M_structures: Total equivalent number of structures per die (M).
                          每个 Die 包含的等效结构总数 (M)。
            F_target: Target cumulative failure rate threshold (e.g., 100 ppm = 1e-4).
                      目标累积失效概率阈值（例如 100 ppm 即 1e-4）。
        """
        self.M = M_structures
        # Calculate target cumulative hazard / 计算目标累积风险得分
        self.target_hazard = -np.log(1.0 - F_target)

    def _generate_inner_die_grid(self, valid_dies_x: np.ndarray, valid_dies_y: np.ndarray, 
                                 N_samples_per_dim: int) -> tuple[np.ndarray, np.ndarray, int]:
        """
        Generate a high-density (N x N) micro-spatial query grid inside each valid die.
        This perfectly restores the core spatial logic from test_predictor.py.
        
        在每个合法的 Die 内部建立 (N x N) 的高密度微观空间查询网格。
        这完美还原了 test_predictor.py 中的核心空间逻辑。
        
        Args:
            valid_dies_x, valid_dies_y: Macro coordinates of dies. / Die 的宏观坐标。
            N_samples_per_dim: Number of samples along one dimension inside a die.
                               一个 Die 内部单维度的采样点数。
                               
        Returns:
            x_die_grid: Shape (n_dies, N_inner). X coordinates for inner-die samples.
            y_die_grid: Shape (n_dies, N_inner). Y coordinates for inner-die samples.
            N_inner: Total samples per die (N_samples_per_dim ** 2).
        """
        D = len(valid_dies_x)  # Total number of valid dies / 合法 Die 的总数
        N_inner = N_samples_per_dim * N_samples_per_dim  # Samples per die / 每个 Die 的总微观点数
        
        x_die_grid = np.zeros((D, N_inner))
        y_die_grid = np.zeros((D, N_inner))
        
        # Define microscopic boundary offsets inside a die (e.g., extending from -0.45 to 0.45)
        # 定义一个 Die 内部的微观边界偏移（例如在 [-0.45, 0.45] 之间延展）
        local_offsets = np.linspace(-0.45, 0.45, N_samples_per_dim)
        
        # True bidirectional (x, y) spatial densification / 真正的双向 (x, y) 空间坐标密集化
        dx, dy = np.meshgrid(local_offsets, local_offsets)
        dx_flat = dx.flatten()
        dy_flat = dy.flatten()
        
        for i in range(D):
            x_die_grid[i, :] = valid_dies_x[i] + dx_flat
            y_die_grid[i, :] = valid_dies_y[i] + dy_flat
            
        return x_die_grid, y_die_grid, N_inner

    def _interpolate_wafer_surface(self, x_measured: np.ndarray, y_measured: np.ndarray, 
                                   measured_values: np.ndarray, x_query_grid: np.ndarray, 
                                   y_query_grid: np.ndarray) -> np.ndarray:
        """
        Extrapolate high-density dimensional surfaces across the wafer using Spatial Kriging (GPR).
        
        使用空间高斯过程（Kriging），根据已知测点外推预测整芯片的高密度尺寸曲面。
        
        Args:
            x_measured, y_measured: Measured macro coordinates. / 已知测量的宏观坐标。
            measured_values: Values at measured points. / 测量点处的值。
            x_query_grid, y_query_grid: High-density grids generated by _generate_inner_die_grid.
                                        由 _generate_inner_die_grid 生成的高密度网格。
        Returns:
            np.ndarray: Interpolated values with shape (n_dies, n_inner_samples).
                        形状为 (n_dies, n_inner_samples) 的插值结果。
        """
        # 1. Train the spatial interpolator / 训练空间插值器
        X_train = np.column_stack([x_measured, y_measured])
        kernel = ConstantKernel(1.0) * RBF(length_scale=3.0) + WhiteKernel(noise_level=0.05)
        gpr = GaussianProcessRegressor(kernel=kernel, normalize_y=True, random_state=42)
        gpr.fit(X_train, measured_values)
        
        # 2. Evaluate all high-density points inside all dies / 对所有 Die 内部的高密度打点进行评估
        X_query = np.column_stack([x_query_grid.flatten(), y_query_grid.flatten()])
        pred_flat = gpr.predict(X_query)
        
        # 3. Reshape back to wafer matrix format / 恢复成晶圆矩阵形状
        return pred_flat.reshape(x_query_grid.shape)

    def _solve_lifetime_vectorized(self, beta_matrix: np.ndarray, eta_matrix: np.ndarray) -> np.ndarray:
        """
        Universal Vectorized Newton-Raphson Solver based on Weakest Link Theory.
        Solves: Sum_{i} (t / eta_i)^beta_i - (Target_Hazard / M) = 0
        
        基于最薄弱环节理论的通用向量化牛顿-拉夫逊求解器。
        求解方程: Sum_{i} (t / eta_i)^beta_i - (目标风险 / M) = 0
        
        Args:
            beta_matrix: Shape (n_dies, n_elements). / 形状为 (n_dies, n_elements)。
            eta_matrix: Shape (n_dies, n_elements). / 形状为 (n_dies, n_elements)。
            
        Returns:
            t: Shape (n_dies,). The predicted lifetimes. / 形状为 (n_dies,) 的预测寿命数组。
        """
        n_dies, n_elements = beta_matrix.shape
        scaled_target = self.target_hazard / self.M
        
        # Initialize lifetime estimate using geometric mean to prevent numerical overflow
        # 使用几何平均值安全初始化寿命，防止浮点溢出
        t = np.exp(np.mean(np.log(eta_matrix), axis=1))
        
        for _ in range(50):
            t_col = t.reshape(-1, 1)
            # Clip safely to avoid exp/log overflow / 安全裁剪以规避浮点数溢出
            norm_t = np.clip(t_col / eta_matrix, 1e-20, 1e20)
            risk_term = norm_t ** beta_matrix
            
            f_val = np.sum(risk_term, axis=1) - scaled_target
            f_prime = np.sum((beta_matrix / t_col) * risk_term, axis=1)
            
            # Newton step / 牛顿迭代步长
            t = t - f_val / (f_prime + 1e-15)
            # Boundary guard: prevent negative lifetime / 边界保护：防止出现负寿命
            t = np.maximum(t, 1e-5)
            
        return t

    def _solve_lifetime_log_vectorized(self, beta_matrix: np.ndarray,
                                       ln_eta_matrix: np.ndarray) -> np.ndarray:
        """Solve weakest-link lifetime directly in log space.

        For ``x = ln(t)``, the target equation is

            log(sum(exp(beta_i * (x - ln_eta_i)))) = log(target_hazard / M).

        A log-sum-exp Newton iteration avoids materializing unit-level ``eta``
        values, which may legitimately exceed the float64 exponential range.
        """
        beta_matrix = np.asarray(beta_matrix, dtype=float)
        ln_eta_matrix = np.asarray(ln_eta_matrix, dtype=float)

        if beta_matrix.shape != ln_eta_matrix.shape:
            raise ValueError(
                f"beta/ln_eta shape mismatch: {beta_matrix.shape} vs {ln_eta_matrix.shape}"
            )
        if not np.all(np.isfinite(beta_matrix)) or np.any(beta_matrix <= 0.0):
            raise ValueError("Weakest-link solve requires finite, positive beta values.")
        if not np.all(np.isfinite(ln_eta_matrix)):
            raise ValueError("Weakest-link solve requires finite ln(eta) values.")

        n_elements = beta_matrix.shape[1]
        log_target = np.log(self.target_hazard / self.M)

        # This initialization assigns at most an equal share of the target
        # hazard to every element, providing a finite lower bracket.
        log_share_target = log_target - np.log(n_elements)
        log_t = np.min(
            ln_eta_matrix + log_share_target / beta_matrix,
            axis=1,
        )

        for _ in range(50):
            log_risk = beta_matrix * (log_t[:, None] - ln_eta_matrix)
            row_max = np.max(log_risk, axis=1, keepdims=True)
            scaled_risk = np.exp(log_risk - row_max)
            scaled_sum = np.sum(scaled_risk, axis=1)

            log_hazard = row_max[:, 0] + np.log(scaled_sum)
            derivative = (
                np.sum(beta_matrix * scaled_risk, axis=1) / scaled_sum
            )
            step = (log_hazard - log_target) / derivative
            log_t -= step

            if np.max(np.abs(step)) < 1e-12:
                break

        # Downstream classifiers currently consume ordinary lifetimes. Keep
        # that public contract while guaranteeing a finite, positive result.
        float_info = np.finfo(float)
        log_t = np.clip(log_t, np.log(float_info.tiny), np.log(float_info.max))
        return np.exp(log_t)

    @abstractmethod
    def predict_die_lifetimes(self, x_die: np.ndarray, y_die: np.ndarray, 
                              vl_data: np.ndarray, ll_data: np.ndarray, 
                              N_samples_per_dim: int = 10) -> np.ndarray:
        """
        Execute the top-level engine to compute the weakest link lifetime map.
        Must be implemented by subclasses.
        
        执行高层流水线以计算最薄弱环节寿命图。必须由子类实现。
        """
        pass


# ==============================================================================
# 3. GPR Wafer Engine / GPR 机器学习大一统晶圆模型
# ==============================================================================
class GPRWaferEngine(BaseWaferEngine):
    """
    Engine tailored for joint Machine Learning (GPR) models.
    
    专门针对联合机器学习（GPR）模型定制的晶圆级流水线。
    """
    def __init__(self, unit_model_joint: BaseTDDBModel, M_structures: float = 1e6, F_target: float = 1e-4):
        super().__init__(M_structures, F_target)
        self.model_joint = unit_model_joint

    def predict_die_lifetimes(self, x_die: np.ndarray, y_die: np.ndarray, 
                              vl_data: np.ndarray, ll_data: np.ndarray, 
                              N_samples_per_dim: int = 10) -> np.ndarray:
        n_dies = len(x_die)
        
        # 1. Generate actual 2D microscopic spatial grids (x_grid, y_grid)
        # 1. 建立真正的微观二维空间网格 (x_grid, y_grid)
        x_grid, y_grid, N_inner = self._generate_inner_die_grid(x_die, y_die, N_samples_per_dim)
        
        # 2. Execute spatial surface regression interpolation in both X and Y directions
        # 2. 在 X 与 Y 方向上执行真正的空间曲面回归插值
        vl_interpolated = self._interpolate_wafer_surface(x_die, y_die, vl_data, x_grid, y_grid)
        ll_interpolated = self._interpolate_wafer_surface(x_die, y_die, ll_data, x_grid, y_grid)
        
        # 3. Flatten into the standard 2D feature matrix required by the Unit GPR Model
        # 3. 转换成符合微观 Unit GPR 模型要求的特征输入: (n_dies * N_inner, 2)
        X_unit = np.column_stack([vl_interpolated.flatten(), ll_interpolated.flatten()])
        
        # 4. Perform joint microscopic prediction / 4. 执行微观联合预测
        beta_pred, eta_pred = self.model_joint.predict_weibull_params(X_unit)
        
        # Reshape to Die-level grids / 重塑回 Die 级网格
        beta_matrix = beta_pred.reshape((n_dies, N_inner))
        eta_matrix = eta_pred.reshape((n_dies, N_inner))
        
        # 5. Solve macroscopic system-level weakest-link / 5. 宏观系统级最薄弱环节求解
        return self._solve_lifetime_vectorized(beta_matrix, eta_matrix)


# ==============================================================================
# 4. DPM Wafer Engine / DPM 纯物理机制大一统晶圆模型
# ==============================================================================
class DPMWaferEngine(BaseWaferEngine):
    """
    Engine tailored for physics-based models (DPM) where via and line are modeled 
    separately but strictly combined at the die level via Weakest Link Theory.
    
    专门针对 DPM 纯物理模型的晶圆级流水线。
    Via 和 Line 在微观上独立建模，但在 Die 级别通过最薄弱环节理论严格联合汇总。
    """
    def __init__(self, unit_model_via: BaseTDDBModel, unit_model_line: BaseTDDBModel,
                 M_structures: float = 1e6, F_target: float = 1e-4):
        super().__init__(M_structures, F_target)
        self.model_via = unit_model_via
        self.model_line = unit_model_line

    def predict_die_lifetimes(self, x_die: np.ndarray, y_die: np.ndarray, 
                              vl_data: np.ndarray, ll_data: np.ndarray, 
                              N_samples_per_dim: int = 10) -> np.ndarray:
        n_dies = len(x_die)
        
        # 1. Generate actual 2D microscopic spatial grids (x_grid, y_grid)
        # 1. 建立真正的微观二维空间网格 (x_grid, y_grid)
        x_grid, y_grid, N_inner = self._generate_inner_die_grid(x_die, y_die, N_samples_per_dim)
        
        # 2. Execute spatial surface regression interpolation in both X and Y directions
        # 2. 在 X 与 Y 方向上执行真正的空间曲面回归插值
        vl_interpolated = self._interpolate_wafer_surface(x_die, y_die, vl_data, x_grid, y_grid)
        ll_interpolated = self._interpolate_wafer_surface(x_die, y_die, ll_data, x_grid, y_grid)
        
        X_unit = np.column_stack([vl_interpolated.flatten(), ll_interpolated.flatten()])
        
        # 3. Calculate separate micro-physics models for Via and Line
        # 3. 分别计算 Via 和 Line 的独立微观物理模型
        beta_via, ln_eta_via = self.model_via.predict_weibull_log_params(X_unit)
        beta_line, ln_eta_line = self.model_line.predict_weibull_log_params(X_unit)
        
        # Reshape to separate Die-level grids / 重塑回独立的 Die 级网格
        beta_via_mat = beta_via.reshape((n_dies, N_inner))
        ln_eta_via_mat = ln_eta_via.reshape((n_dies, N_inner))
        
        beta_line_mat = beta_line.reshape((n_dies, N_inner))
        ln_eta_line_mat = ln_eta_line.reshape((n_dies, N_inner))
        
        # 4. CRITICAL: Weakest Link Physical Risk Integration
        #    Horizontal concatenation (axis=1) perfectly aligns with the multiplication 
        #    rule of Joint Reliability without formula coupling!
        # 4. 核心：最薄弱环节物理风险集成
        #    沿着 axis=1 横向拼接，完美契合联合可靠性连乘法则，且无需进行公式耦合！
        beta_matrix = np.concatenate([beta_via_mat, beta_line_mat], axis=1) # Shape: (n_dies, 2 * N_inner)
        ln_eta_matrix = np.concatenate([ln_eta_via_mat, ln_eta_line_mat], axis=1)  # Shape: (n_dies, 2 * N_inner)
        
        # 5. Solve macroscopic system-level weakest-link / 5. 宏观系统级最薄弱环节求解
        return self._solve_lifetime_log_vectorized(beta_matrix, ln_eta_matrix)
